# Generated by Django 6.0.4 on 2026-05-23 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='citas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='configuracionclinica',
            options={},
        ),
        migrations.AlterModelOptions(
            name='doctores',
            options={},
        ),
        migrations.AlterModelOptions(
            name='especialidades',
            options={},
        ),
        migrations.AlterModelOptions(
            name='estadoscita',
            options={},
        ),
        migrations.AlterModelOptions(
            name='motivosconsulta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notasclinicas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pacientes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pagos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recordatorios',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tipospago',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={},
        ),
    ]
