# Generated by Django 6.0.4 on 2026-06-15 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='estado',
            field=models.CharField(blank=True, default='pagado', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pagos',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagos',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagos',
            name='registrado_por',
            field=models.ForeignKey(blank=True, db_column='registrado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pagos_registrados', to='core.usuarios'),
        ),
    ]
